# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c76ef3c9b68ac795fcd3528c6679ee1b142bdef5c076b9d9b83cdd7335398231365cc257c194a6e0ee937008bc9aeb275353d6acc7efced9ed2d0ee216985d7

test:
  secret_key_base: e4c318482542e1bc520615420fd9612f9b7f3fedf5249ef9088b1e3e86320894126ed415588c15b28f4ec12ae87f960374dfbd6e60ff37190f4b7a5106f72fc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
